
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.ViewWidgets.Orders
{
	public partial class OrderDocumentsView
	{
		private global::Gtk.VBox vboxDocuments;

		private global::Gtk.HBox hbox19;

		private global::Gtk.VBox vbox9;

		private global::Gtk.HBox hbox20;

		private global::Gamma.GtkWidgets.yButton ybtnAddExistingDoc;

		private global::Gamma.GtkWidgets.yButton ybtnAddM2ProxyForThisOrder;

		private global::Gamma.GtkWidgets.yButton ybtnAddCurrentContract;

		private global::Gamma.GtkWidgets.yButton ybtnRemoveExistingDoc;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTreeView ytreeDocuments;

		private global::Gtk.HBox hbox23;

		private global::Gamma.GtkWidgets.yButton ybtnViewDoc;

		private global::Gamma.GtkWidgets.yButton ybtnPrintSelected;

		private global::Gamma.GtkWidgets.yButton ybtnOpenPrintDlg;

		private global::Vodovoz.Dialogs.Email.SendDocumentByEmailView sendDocumentByEmailView;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.ViewWidgets.Orders.OrderDocumentsView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.ViewWidgets.Orders.OrderDocumentsView";
			// Container child Vodovoz.ViewWidgets.Orders.OrderDocumentsView.Gtk.Container+ContainerChild
			this.vboxDocuments = new global::Gtk.VBox();
			this.vboxDocuments.Name = "vboxDocuments";
			this.vboxDocuments.Spacing = 6;
			// Container child vboxDocuments.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.ybtnAddExistingDoc = new global::Gamma.GtkWidgets.yButton();
			this.ybtnAddExistingDoc.CanFocus = true;
			this.ybtnAddExistingDoc.Name = "ybtnAddExistingDoc";
			this.ybtnAddExistingDoc.UseUnderline = true;
			this.ybtnAddExistingDoc.Label = global::Mono.Unix.Catalog.GetString("Документы прошлых заказов");
			global::Gtk.Image w1 = new global::Gtk.Image();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
			this.ybtnAddExistingDoc.Image = w1;
			this.hbox20.Add(this.ybtnAddExistingDoc);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.ybtnAddExistingDoc]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.ybtnAddM2ProxyForThisOrder = new global::Gamma.GtkWidgets.yButton();
			this.ybtnAddM2ProxyForThisOrder.CanFocus = true;
			this.ybtnAddM2ProxyForThisOrder.Name = "ybtnAddM2ProxyForThisOrder";
			this.ybtnAddM2ProxyForThisOrder.UseUnderline = true;
			this.ybtnAddM2ProxyForThisOrder.Label = global::Mono.Unix.Catalog.GetString("Доверенность М-2 для этого заказа");
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
			this.ybtnAddM2ProxyForThisOrder.Image = w3;
			this.hbox20.Add(this.ybtnAddM2ProxyForThisOrder);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.ybtnAddM2ProxyForThisOrder]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.ybtnAddCurrentContract = new global::Gamma.GtkWidgets.yButton();
			this.ybtnAddCurrentContract.CanFocus = true;
			this.ybtnAddCurrentContract.Name = "ybtnAddCurrentContract";
			this.ybtnAddCurrentContract.UseUnderline = true;
			this.ybtnAddCurrentContract.Label = global::Mono.Unix.Catalog.GetString("Договор");
			global::Gtk.Image w5 = new global::Gtk.Image();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
			this.ybtnAddCurrentContract.Image = w5;
			this.hbox20.Add(this.ybtnAddCurrentContract);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.ybtnAddCurrentContract]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.ybtnRemoveExistingDoc = new global::Gamma.GtkWidgets.yButton();
			this.ybtnRemoveExistingDoc.CanFocus = true;
			this.ybtnRemoveExistingDoc.Name = "ybtnRemoveExistingDoc";
			this.ybtnRemoveExistingDoc.UseUnderline = true;
			this.ybtnRemoveExistingDoc.Label = global::Mono.Unix.Catalog.GetString("Удалить документы прошлых заказов");
			global::Gtk.Image w7 = new global::Gtk.Image();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-remove", global::Gtk.IconSize.Menu);
			this.ybtnRemoveExistingDoc.Image = w7;
			this.hbox20.Add(this.ybtnRemoveExistingDoc);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.ybtnRemoveExistingDoc]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox9.Add(this.hbox20);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox20]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytreeDocuments = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeDocuments.CanFocus = true;
			this.ytreeDocuments.Name = "ytreeDocuments";
			this.GtkScrolledWindow.Add(this.ytreeDocuments);
			this.vbox9.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.GtkScrolledWindow]));
			w11.Position = 1;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.ybtnViewDoc = new global::Gamma.GtkWidgets.yButton();
			this.ybtnViewDoc.CanFocus = true;
			this.ybtnViewDoc.Name = "ybtnViewDoc";
			this.ybtnViewDoc.UseUnderline = true;
			this.ybtnViewDoc.Label = global::Mono.Unix.Catalog.GetString("Просмотреть  документ");
			global::Gtk.Image w12 = new global::Gtk.Image();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-find", global::Gtk.IconSize.Menu);
			this.ybtnViewDoc.Image = w12;
			this.hbox23.Add(this.ybtnViewDoc);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.ybtnViewDoc]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.ybtnPrintSelected = new global::Gamma.GtkWidgets.yButton();
			this.ybtnPrintSelected.CanFocus = true;
			this.ybtnPrintSelected.Name = "ybtnPrintSelected";
			this.ybtnPrintSelected.UseUnderline = true;
			this.ybtnPrintSelected.Label = global::Mono.Unix.Catalog.GetString("Печать выделенных");
			global::Gtk.Image w14 = new global::Gtk.Image();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-print", global::Gtk.IconSize.Menu);
			this.ybtnPrintSelected.Image = w14;
			this.hbox23.Add(this.ybtnPrintSelected);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.ybtnPrintSelected]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.ybtnOpenPrintDlg = new global::Gamma.GtkWidgets.yButton();
			this.ybtnOpenPrintDlg.CanFocus = true;
			this.ybtnOpenPrintDlg.Name = "ybtnOpenPrintDlg";
			this.ybtnOpenPrintDlg.UseUnderline = true;
			this.ybtnOpenPrintDlg.Label = global::Mono.Unix.Catalog.GetString("Диалог печати...");
			global::Gtk.Image w16 = new global::Gtk.Image();
			w16.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-print", global::Gtk.IconSize.Menu);
			this.ybtnOpenPrintDlg.Image = w16;
			this.hbox23.Add(this.ybtnOpenPrintDlg);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.ybtnOpenPrintDlg]));
			w17.PackType = ((global::Gtk.PackType)(1));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox9.Add(this.hbox23);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox23]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox19.Add(this.vbox9);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.vbox9]));
			w19.Position = 0;
			// Container child hbox19.Gtk.Box+BoxChild
			this.sendDocumentByEmailView = new global::Vodovoz.Dialogs.Email.SendDocumentByEmailView();
			this.sendDocumentByEmailView.Events = ((global::Gdk.EventMask)(256));
			this.sendDocumentByEmailView.Name = "sendDocumentByEmailView";
			this.hbox19.Add(this.sendDocumentByEmailView);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.sendDocumentByEmailView]));
			w20.Position = 1;
			this.vboxDocuments.Add(this.hbox19);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vboxDocuments[this.hbox19]));
			w21.Position = 0;
			this.Add(this.vboxDocuments);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
