
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.JournalViewers
{
	public partial class OrdersDocumentsView
	{
		private global::Gtk.VBox vboxMain;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hboxEntries;

		private global::Gtk.Label label3;

		private global::Gamma.Widgets.yValidatedEntry yvalidatedOrderNum;

		private global::Gtk.Label label2;

		private global::QS.Widgets.GtkUI.RepresentationEntry representationEntryCounterparty;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::QSOrmProject.RepresentationTreeView datatreeviewOrderDocuments;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.JournalViewers.OrdersDocumentsView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.JournalViewers.OrdersDocumentsView";
			// Container child Vodovoz.JournalViewers.OrdersDocumentsView.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			this.vboxMain.BorderWidth = ((uint)(6));
			// Container child vboxMain.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Документы заказа:");
			this.vboxMain.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hboxEntries = new global::Gtk.HBox();
			this.hboxEntries.Name = "hboxEntries";
			this.hboxEntries.Spacing = 6;
			// Container child hboxEntries.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Заказ:");
			this.hboxEntries.Add(this.label3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxEntries[this.label3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hboxEntries.Gtk.Box+BoxChild
			this.yvalidatedOrderNum = new global::Gamma.Widgets.yValidatedEntry();
			this.yvalidatedOrderNum.CanFocus = true;
			this.yvalidatedOrderNum.Name = "yvalidatedOrderNum";
			this.yvalidatedOrderNum.IsEditable = true;
			this.yvalidatedOrderNum.InvisibleChar = '•';
			this.hboxEntries.Add(this.yvalidatedOrderNum);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxEntries[this.yvalidatedOrderNum]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hboxEntries.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Контрагент:");
			this.hboxEntries.Add(this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxEntries[this.label2]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hboxEntries.Gtk.Box+BoxChild
			this.representationEntryCounterparty = new global::QS.Widgets.GtkUI.RepresentationEntry();
			this.representationEntryCounterparty.Events = ((global::Gdk.EventMask)(256));
			this.representationEntryCounterparty.Name = "representationEntryCounterparty";
			this.hboxEntries.Add(this.representationEntryCounterparty);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxEntries[this.representationEntryCounterparty]));
			w5.Position = 3;
			this.vboxMain.Add(this.hboxEntries);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hboxEntries]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.datatreeviewOrderDocuments = new global::QSOrmProject.RepresentationTreeView();
			this.datatreeviewOrderDocuments.CanFocus = true;
			this.datatreeviewOrderDocuments.Name = "datatreeviewOrderDocuments";
			this.GtkScrolledWindow.Add(this.datatreeviewOrderDocuments);
			this.vboxMain.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.GtkScrolledWindow]));
			w8.Position = 2;
			this.Add(this.vboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
