
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Orders
{
	public partial class AddExistingDocumentsView
	{
		private global::Gtk.VBox vboxMain;

		private global::Vodovoz.ViewWidgets.CounterpartyDocumentsView counterpartyDocumentsView;

		private global::Gtk.VBox vboxOrdersDocuments;

		private global::Vodovoz.ViewWidgets.Orders.BaseOrdersDocumentsView baseOrdersDocumentsView;

		private global::Gtk.HBox hbox4;

		private global::Gamma.GtkWidgets.yButton ybtnAddSelectedDocs;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Orders.AddExistingDocumentsView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Orders.AddExistingDocumentsView";
			// Container child Vodovoz.Views.Orders.AddExistingDocumentsView.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.counterpartyDocumentsView = new global::Vodovoz.ViewWidgets.CounterpartyDocumentsView();
			this.counterpartyDocumentsView.Events = ((global::Gdk.EventMask)(256));
			this.counterpartyDocumentsView.Name = "counterpartyDocumentsView";
			this.vboxMain.Add(this.counterpartyDocumentsView);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.counterpartyDocumentsView]));
			w1.Position = 0;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.vboxOrdersDocuments = new global::Gtk.VBox();
			this.vboxOrdersDocuments.Name = "vboxOrdersDocuments";
			this.vboxOrdersDocuments.Spacing = 6;
			// Container child vboxOrdersDocuments.Gtk.Box+BoxChild
			this.baseOrdersDocumentsView = new global::Vodovoz.ViewWidgets.Orders.BaseOrdersDocumentsView();
			this.baseOrdersDocumentsView.Events = ((global::Gdk.EventMask)(256));
			this.baseOrdersDocumentsView.Name = "baseOrdersDocumentsView";
			this.vboxOrdersDocuments.Add(this.baseOrdersDocumentsView);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxOrdersDocuments[this.baseOrdersDocumentsView]));
			w2.Position = 0;
			this.vboxMain.Add(this.vboxOrdersDocuments);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.vboxOrdersDocuments]));
			w3.Position = 1;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.ybtnAddSelectedDocs = new global::Gamma.GtkWidgets.yButton();
			this.ybtnAddSelectedDocs.CanFocus = true;
			this.ybtnAddSelectedDocs.Name = "ybtnAddSelectedDocs";
			this.ybtnAddSelectedDocs.UseUnderline = true;
			this.ybtnAddSelectedDocs.Label = global::Mono.Unix.Catalog.GetString("Добавить выбранные документы");
			this.hbox4.Add(this.ybtnAddSelectedDocs);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.ybtnAddSelectedDocs]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.vboxMain.Add(this.hbox4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hbox4]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.Add(this.vboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
