
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.ViewWidgets.Orders
{
	public partial class OrderMovementItemsView
	{
		private global::Gtk.VBox vboxMain;

		private global::Gamma.GtkWidgets.yLabel ylblTitle;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTreeView ytreeViewMovementItems;

		private global::Gtk.HBox hboxBtns;

		private global::Gamma.GtkWidgets.yButton ybtnAddMovementItemToClient;

		private global::Gamma.GtkWidgets.yButton ybtnAddMovementItemFromClient;

		private global::Gamma.GtkWidgets.yButton ybtnRemoveMovementItem;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.ViewWidgets.Orders.OrderMovementItemsView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.ViewWidgets.Orders.OrderMovementItemsView";
			// Container child Vodovoz.ViewWidgets.Orders.OrderMovementItemsView.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.ylblTitle = new global::Gamma.GtkWidgets.yLabel();
			this.ylblTitle.Name = "ylblTitle";
			this.ylblTitle.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Оборудование</b>");
			this.ylblTitle.UseMarkup = true;
			this.vboxMain.Add(this.ylblTitle);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.ylblTitle]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytreeViewMovementItems = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeViewMovementItems.CanFocus = true;
			this.ytreeViewMovementItems.Name = "ytreeViewMovementItems";
			this.GtkScrolledWindow.Add(this.ytreeViewMovementItems);
			this.vboxMain.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hboxBtns = new global::Gtk.HBox();
			this.hboxBtns.Name = "hboxBtns";
			this.hboxBtns.Spacing = 6;
			// Container child hboxBtns.Gtk.Box+BoxChild
			this.ybtnAddMovementItemToClient = new global::Gamma.GtkWidgets.yButton();
			this.ybtnAddMovementItemToClient.CanFocus = true;
			this.ybtnAddMovementItemToClient.Name = "ybtnAddMovementItemToClient";
			this.ybtnAddMovementItemToClient.UseUnderline = true;
			this.ybtnAddMovementItemToClient.Label = global::Mono.Unix.Catalog.GetString("Оборудование к клиенту");
			this.hboxBtns.Add(this.ybtnAddMovementItemToClient);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxBtns[this.ybtnAddMovementItemToClient]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hboxBtns.Gtk.Box+BoxChild
			this.ybtnAddMovementItemFromClient = new global::Gamma.GtkWidgets.yButton();
			this.ybtnAddMovementItemFromClient.CanFocus = true;
			this.ybtnAddMovementItemFromClient.Name = "ybtnAddMovementItemFromClient";
			this.ybtnAddMovementItemFromClient.UseUnderline = true;
			this.ybtnAddMovementItemFromClient.Label = global::Mono.Unix.Catalog.GetString("Оборудование от клиента");
			this.hboxBtns.Add(this.ybtnAddMovementItemFromClient);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxBtns[this.ybtnAddMovementItemFromClient]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hboxBtns.Gtk.Box+BoxChild
			this.ybtnRemoveMovementItem = new global::Gamma.GtkWidgets.yButton();
			this.ybtnRemoveMovementItem.CanFocus = true;
			this.ybtnRemoveMovementItem.Name = "ybtnRemoveMovementItem";
			this.ybtnRemoveMovementItem.UseUnderline = true;
			this.ybtnRemoveMovementItem.Label = global::Mono.Unix.Catalog.GetString("Удалить оборудование");
			this.hboxBtns.Add(this.ybtnRemoveMovementItem);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxBtns[this.ybtnRemoveMovementItem]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.vboxMain.Add(this.hboxBtns);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hboxBtns]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.Add(this.vboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
