
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Orders
{
	public partial class DiscountReasonView
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gamma.GtkWidgets.yButton buttonSave;

		private global::Gamma.GtkWidgets.yButton buttonCancel;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Table table3;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label2;

		private global::Gamma.GtkWidgets.yCheckButton checkIsArchive;

		private global::Gtk.HBox hbox4;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label3;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label1;

		private global::Gamma.GtkWidgets.yEntry entryName;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label labelPermission;

		private global::Gtk.Label labelSkill;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Entry entry2;

		private global::Gtk.Button buttonChoosePermission;

		private global::Gtk.Button buttonClearPermission;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label label6;

		private global::Gtk.Label label5;

		private global::Gtk.Entry entry4;

		private global::Gtk.Label label4;

		private global::Gtk.Entry entry3;

		private global::Gtk.ComboBox combobox3;

		private global::Gtk.HBox hbox9;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label7;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Label label8;

		private global::Gtk.Entry entry6;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Button button265;

		private global::Gtk.Button button266;

		private global::Gtk.HBox hbox13;

		private global::Gamma.GtkWidgets.yCheckButton ycheckSelfdelivery;

		private global::Gamma.GtkWidgets.yHBox yhbox2;

		private global::Gamma.GtkWidgets.yCheckButton ycheckForPromotionalSet;

		private global::Gtk.HBox hbox15;

		private global::Gamma.GtkWidgets.yCheckButton ycheckIncludeReclamation;

		private global::Gtk.HBox hbox16;

		private global::Gtk.HBox hbox17;

		private global::Gtk.Label label9;

		private global::Gamma.GtkWidgets.yCheckButton ycheckWithOtherDiscounts;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.Table table1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Orders.DiscountReasonView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Orders.DiscountReasonView";
			// Container child Vodovoz.Views.Orders.DiscountReasonView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonSave = new global::Gamma.GtkWidgets.yButton();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
			global::Gtk.Image w1 = new global::Gtk.Image();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-floppy", global::Gtk.IconSize.Menu);
			this.buttonSave.Image = w1;
			this.hbox1.Add(this.buttonSave);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonSave]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gamma.GtkWidgets.yButton();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Отменить");
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-close", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w3;
			this.hbox1.Add(this.buttonCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonCancel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table(((uint)(1)), ((uint)(3)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("В архиве:");
			this.label2.Justify = ((global::Gtk.Justification)(1));
			this.hbox2.Add(this.label2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label2]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.checkIsArchive = new global::Gamma.GtkWidgets.yCheckButton();
			this.checkIsArchive.CanFocus = true;
			this.checkIsArchive.Name = "checkIsArchive";
			this.checkIsArchive.Label = "";
			this.checkIsArchive.DrawIndicator = true;
			this.checkIsArchive.UseUnderline = true;
			this.hbox2.Add(this.checkIsArchive);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.checkIsArchive]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.table3.Add(this.hbox2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3[this.hbox2]));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Тип");
			this.hbox5.Add(this.label3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label3]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			this.hbox4.Add(this.hbox5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox5]));
			w11.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Название:");
			this.label1.Justify = ((global::Gtk.Justification)(1));
			this.hbox3.Add(this.label1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label1]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entryName = new global::Gamma.GtkWidgets.yEntry();
			this.entryName.CanFocus = true;
			this.entryName.Name = "entryName";
			this.entryName.IsEditable = true;
			this.entryName.InvisibleChar = '•';
			this.hbox3.Add(this.entryName);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entryName]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.hbox4.Add(this.hbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox3]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.table3.Add(this.hbox4);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3[this.hbox4]));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add(this.table3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table3]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.labelPermission = new global::Gtk.Label();
			this.labelPermission.Name = "labelPermission";
			this.labelPermission.LabelProp = global::Mono.Unix.Catalog.GetString("Права");
			this.hbox6.Add(this.labelPermission);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.labelPermission]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.labelSkill = new global::Gtk.Label();
			this.labelSkill.Name = "labelSkill";
			this.labelSkill.LabelProp = global::Mono.Unix.Catalog.GetString("Квалификация");
			this.hbox6.Add(this.labelSkill);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.labelSkill]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '•';
			this.hbox7.Add(this.entry2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entry2]));
			w19.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.buttonChoosePermission = new global::Gtk.Button();
			this.buttonChoosePermission.CanFocus = true;
			this.buttonChoosePermission.Name = "buttonChoosePermission";
			this.buttonChoosePermission.UseUnderline = true;
			this.buttonChoosePermission.Label = global::Mono.Unix.Catalog.GetString("Choose");
			this.hbox7.Add(this.buttonChoosePermission);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.buttonChoosePermission]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.buttonClearPermission = new global::Gtk.Button();
			this.buttonClearPermission.CanFocus = true;
			this.buttonClearPermission.Name = "buttonClearPermission";
			this.buttonClearPermission.UseUnderline = true;
			this.buttonClearPermission.Label = global::Mono.Unix.Catalog.GetString("Clear");
			this.hbox7.Add(this.buttonClearPermission);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.buttonClearPermission]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.hbox6.Add(this.hbox7);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hbox7]));
			w22.Position = 4;
			this.vbox1.Add(this.hbox6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox6]));
			w23.Position = 3;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Скидки:");
			this.hbox8.Add(this.label6);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label6]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Мин");
			this.hbox8.Add(this.label5);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label5]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.entry4 = new global::Gtk.Entry();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '•';
			this.hbox8.Add(this.entry4);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.entry4]));
			w26.Position = 2;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Макс");
			this.hbox8.Add(this.label4);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label4]));
			w27.Position = 3;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '•';
			this.hbox8.Add(this.entry3);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.entry3]));
			w28.Position = 4;
			// Container child hbox8.Gtk.Box+BoxChild
			this.combobox3 = global::Gtk.ComboBox.NewText();
			this.combobox3.Name = "combobox3";
			this.hbox8.Add(this.combobox3);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.combobox3]));
			w29.Position = 5;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox1.Add(this.hbox8);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox8]));
			w30.Position = 4;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Время");
			this.hbox10.Add(this.label7);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label7]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			this.hbox9.Add(this.hbox10);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.hbox10]));
			w32.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Контрагенты");
			this.hbox11.Add(this.label8);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.label8]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.entry6 = new global::Gtk.Entry();
			this.entry6.CanFocus = true;
			this.entry6.Name = "entry6";
			this.entry6.IsEditable = true;
			this.entry6.InvisibleChar = '•';
			this.hbox11.Add(this.entry6);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.entry6]));
			w34.Position = 2;
			// Container child hbox11.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button265 = new global::Gtk.Button();
			this.button265.CanFocus = true;
			this.button265.Name = "button265";
			this.button265.UseUnderline = true;
			this.button265.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.hbox12.Add(this.button265);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.button265]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button266 = new global::Gtk.Button();
			this.button266.CanFocus = true;
			this.button266.Name = "button266";
			this.button266.UseUnderline = true;
			this.button266.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.hbox12.Add(this.button266);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.button266]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			this.hbox11.Add(this.hbox12);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.hbox12]));
			w37.Position = 3;
			w37.Expand = false;
			w37.Fill = false;
			this.hbox9.Add(this.hbox11);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.hbox11]));
			w38.Position = 2;
			this.vbox1.Add(this.hbox9);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox9]));
			w39.Position = 6;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.ycheckSelfdelivery = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckSelfdelivery.CanFocus = true;
			this.ycheckSelfdelivery.Name = "ycheckSelfdelivery";
			this.ycheckSelfdelivery.Label = global::Mono.Unix.Catalog.GetString("Самовывоз");
			this.ycheckSelfdelivery.DrawIndicator = true;
			this.ycheckSelfdelivery.UseUnderline = true;
			this.hbox13.Add(this.ycheckSelfdelivery);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.ycheckSelfdelivery]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.yhbox2 = new global::Gamma.GtkWidgets.yHBox();
			this.yhbox2.Name = "yhbox2";
			this.yhbox2.Spacing = 6;
			// Container child yhbox2.Gtk.Box+BoxChild
			this.ycheckForPromotionalSet = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckForPromotionalSet.CanFocus = true;
			this.ycheckForPromotionalSet.Name = "ycheckForPromotionalSet";
			this.ycheckForPromotionalSet.Label = global::Mono.Unix.Catalog.GetString("Промонабор");
			this.ycheckForPromotionalSet.DrawIndicator = true;
			this.ycheckForPromotionalSet.UseUnderline = true;
			this.yhbox2.Add(this.ycheckForPromotionalSet);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.yhbox2[this.ycheckForPromotionalSet]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			this.hbox13.Add(this.yhbox2);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.yhbox2]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.ycheckIncludeReclamation = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckIncludeReclamation.CanFocus = true;
			this.ycheckIncludeReclamation.Name = "ycheckIncludeReclamation";
			this.ycheckIncludeReclamation.Label = global::Mono.Unix.Catalog.GetString("Обязательная рекламация");
			this.ycheckIncludeReclamation.DrawIndicator = true;
			this.ycheckIncludeReclamation.UseUnderline = true;
			this.hbox15.Add(this.ycheckIncludeReclamation);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.ycheckIncludeReclamation]));
			w43.Position = 0;
			w43.Expand = false;
			w43.Fill = false;
			this.hbox13.Add(this.hbox15);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.hbox15]));
			w44.Position = 2;
			w44.Expand = false;
			w44.Fill = false;
			this.vbox1.Add(this.hbox13);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox13]));
			w45.Position = 7;
			w45.Expand = false;
			w45.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Взаимодействует с другими скидками");
			this.hbox17.Add(this.label9);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.label9]));
			w46.Position = 0;
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.ycheckWithOtherDiscounts = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckWithOtherDiscounts.CanFocus = true;
			this.ycheckWithOtherDiscounts.Name = "ycheckWithOtherDiscounts";
			this.ycheckWithOtherDiscounts.Label = "";
			this.ycheckWithOtherDiscounts.DrawIndicator = true;
			this.ycheckWithOtherDiscounts.UseUnderline = true;
			this.hbox17.Add(this.ycheckWithOtherDiscounts);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.ycheckWithOtherDiscounts]));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			this.hbox16.Add(this.hbox17);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.hbox17]));
			w48.Position = 0;
			w48.Expand = false;
			w48.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText();
			this.combobox1.Name = "combobox1";
			this.hbox16.Add(this.combobox1);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.combobox1]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.hbox16.Add(this.table1);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.table1]));
			w50.Position = 2;
			this.vbox1.Add(this.hbox16);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox16]));
			w51.Position = 8;
			w51.Expand = false;
			w51.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
