
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.ViewWidgets.Orders
{
	public partial class WorkingOnOrderView
	{
		private global::Gtk.VBox vboxMain;

		private global::Gtk.Table tableMain;

		private global::Gamma.Widgets.yEnumComboBox enumDiverCallType;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTextView ytxtManagerComment;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gamma.GtkWidgets.yTextView ytxtTareComment;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gamma.GtkWidgets.yTextView ytxtSalesDepartmentComment;

		private global::Gtk.ScrolledWindow GtkScrolledWindow3;

		private global::Gamma.GtkWidgets.yTextView ytxtODZComment;

		private global::QS.Widgets.GtkUI.SpecialListComboBox specCmbNonReturnTareReasons;

		private global::Gamma.GtkWidgets.yLabel ylblDriverCall;

		private global::Gamma.GtkWidgets.yLabel ylblDriverPhone;

		private global::Gamma.GtkWidgets.yLabel ylblNonReturnTareReason;

		private global::Gamma.GtkWidgets.yLabel ylblNumOfDriverCall;

		private global::Gamma.GtkWidgets.yLabel ylblODZComment;

		private global::Gamma.GtkWidgets.yLabel ylblSalesDepartmentComment;

		private global::Gamma.GtkWidgets.yLabel ylblTareComment;

		private global::Gamma.GtkWidgets.yLabel ylblValueNumOfDriverCall;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.ViewWidgets.Orders.WorkingOnOrderView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.ViewWidgets.Orders.WorkingOnOrderView";
			// Container child Vodovoz.ViewWidgets.Orders.WorkingOnOrderView.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.tableMain = new global::Gtk.Table(((uint)(7)), ((uint)(3)), false);
			this.tableMain.Name = "tableMain";
			this.tableMain.RowSpacing = ((uint)(6));
			this.tableMain.ColumnSpacing = ((uint)(6));
			// Container child tableMain.Gtk.Table+TableChild
			this.enumDiverCallType = new global::Gamma.Widgets.yEnumComboBox();
			this.enumDiverCallType.Name = "enumDiverCallType";
			this.enumDiverCallType.ShowSpecialStateAll = false;
			this.enumDiverCallType.ShowSpecialStateNot = false;
			this.enumDiverCallType.UseShortTitle = false;
			this.enumDiverCallType.DefaultFirst = false;
			this.tableMain.Add(this.enumDiverCallType);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tableMain[this.enumDiverCallType]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytxtManagerComment = new global::Gamma.GtkWidgets.yTextView();
			this.ytxtManagerComment.CanFocus = true;
			this.ytxtManagerComment.Name = "ytxtManagerComment";
			this.GtkScrolledWindow.Add(this.ytxtManagerComment);
			this.tableMain.Add(this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tableMain[this.GtkScrolledWindow]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(3));
			// Container child tableMain.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.ytxtTareComment = new global::Gamma.GtkWidgets.yTextView();
			this.ytxtTareComment.CanFocus = true;
			this.ytxtTareComment.Name = "ytxtTareComment";
			this.GtkScrolledWindow1.Add(this.ytxtTareComment);
			this.tableMain.Add(this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tableMain[this.GtkScrolledWindow1]));
			w5.TopAttach = ((uint)(4));
			w5.BottomAttach = ((uint)(5));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.ytxtSalesDepartmentComment = new global::Gamma.GtkWidgets.yTextView();
			this.ytxtSalesDepartmentComment.CanFocus = true;
			this.ytxtSalesDepartmentComment.Name = "ytxtSalesDepartmentComment";
			this.GtkScrolledWindow2.Add(this.ytxtSalesDepartmentComment);
			this.tableMain.Add(this.GtkScrolledWindow2);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tableMain[this.GtkScrolledWindow2]));
			w7.TopAttach = ((uint)(5));
			w7.BottomAttach = ((uint)(6));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.ytxtODZComment = new global::Gamma.GtkWidgets.yTextView();
			this.ytxtODZComment.CanFocus = true;
			this.ytxtODZComment.Name = "ytxtODZComment";
			this.GtkScrolledWindow3.Add(this.ytxtODZComment);
			this.tableMain.Add(this.GtkScrolledWindow3);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tableMain[this.GtkScrolledWindow3]));
			w9.TopAttach = ((uint)(6));
			w9.BottomAttach = ((uint)(7));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.specCmbNonReturnTareReasons = new global::QS.Widgets.GtkUI.SpecialListComboBox();
			this.specCmbNonReturnTareReasons.Name = "specCmbNonReturnTareReasons";
			this.specCmbNonReturnTareReasons.AddIfNotExist = false;
			this.specCmbNonReturnTareReasons.DefaultFirst = true;
			this.specCmbNonReturnTareReasons.ShowSpecialStateAll = false;
			this.specCmbNonReturnTareReasons.ShowSpecialStateNot = false;
			this.tableMain.Add(this.specCmbNonReturnTareReasons);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tableMain[this.specCmbNonReturnTareReasons]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.ylblDriverCall = new global::Gamma.GtkWidgets.yLabel();
			this.ylblDriverCall.Name = "ylblDriverCall";
			this.ylblDriverCall.Xalign = 1F;
			this.ylblDriverCall.LabelProp = global::Mono.Unix.Catalog.GetString("Отзвон водителя:");
			this.tableMain.Add(this.ylblDriverCall);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tableMain[this.ylblDriverCall]));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.ylblDriverPhone = new global::Gamma.GtkWidgets.yLabel();
			this.ylblDriverPhone.Name = "ylblDriverPhone";
			this.ylblDriverPhone.Xalign = 1F;
			this.ylblDriverPhone.LabelProp = global::Mono.Unix.Catalog.GetString("Водительский телефон:");
			this.tableMain.Add(this.ylblDriverPhone);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tableMain[this.ylblDriverPhone]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.ylblNonReturnTareReason = new global::Gamma.GtkWidgets.yLabel();
			this.ylblNonReturnTareReason.Name = "ylblNonReturnTareReason";
			this.ylblNonReturnTareReason.Xalign = 1F;
			this.ylblNonReturnTareReason.LabelProp = global::Mono.Unix.Catalog.GetString("Причина не сдачи тары:");
			this.tableMain.Add(this.ylblNonReturnTareReason);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tableMain[this.ylblNonReturnTareReason]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.ylblNumOfDriverCall = new global::Gamma.GtkWidgets.yLabel();
			this.ylblNumOfDriverCall.Name = "ylblNumOfDriverCall";
			this.ylblNumOfDriverCall.Xalign = 1F;
			this.ylblNumOfDriverCall.LabelProp = global::Mono.Unix.Catalog.GetString("Номер звонка водителя:");
			this.tableMain.Add(this.ylblNumOfDriverCall);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tableMain[this.ylblNumOfDriverCall]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.ylblODZComment = new global::Gamma.GtkWidgets.yLabel();
			this.ylblODZComment.Name = "ylblODZComment";
			this.ylblODZComment.Xalign = 1F;
			this.ylblODZComment.LabelProp = global::Mono.Unix.Catalog.GetString("Комментарий ОДЗ:");
			this.tableMain.Add(this.ylblODZComment);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tableMain[this.ylblODZComment]));
			w15.TopAttach = ((uint)(6));
			w15.BottomAttach = ((uint)(7));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.ylblSalesDepartmentComment = new global::Gamma.GtkWidgets.yLabel();
			this.ylblSalesDepartmentComment.Name = "ylblSalesDepartmentComment";
			this.ylblSalesDepartmentComment.Xalign = 1F;
			this.ylblSalesDepartmentComment.LabelProp = global::Mono.Unix.Catalog.GetString("Комментарий ОП:");
			this.tableMain.Add(this.ylblSalesDepartmentComment);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tableMain[this.ylblSalesDepartmentComment]));
			w16.TopAttach = ((uint)(5));
			w16.BottomAttach = ((uint)(6));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.ylblTareComment = new global::Gamma.GtkWidgets.yLabel();
			this.ylblTareComment.Name = "ylblTareComment";
			this.ylblTareComment.Xalign = 1F;
			this.ylblTareComment.LabelProp = global::Mono.Unix.Catalog.GetString("Комментарий по таре:");
			this.tableMain.Add(this.ylblTareComment);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tableMain[this.ylblTareComment]));
			w17.TopAttach = ((uint)(4));
			w17.BottomAttach = ((uint)(5));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.ylblValueNumOfDriverCall = new global::Gamma.GtkWidgets.yLabel();
			this.ylblValueNumOfDriverCall.Name = "ylblValueNumOfDriverCall";
			this.ylblValueNumOfDriverCall.Xalign = 0F;
			this.ylblValueNumOfDriverCall.LabelProp = global::Mono.Unix.Catalog.GetString("Значение");
			this.tableMain.Add(this.ylblValueNumOfDriverCall);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tableMain[this.ylblValueNumOfDriverCall]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxMain.Add(this.tableMain);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.tableMain]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			this.Add(this.vboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
