
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.ViewWidgets.Orders
{
	public partial class OrderDepositReturnsItemsView
	{
		private global::Gtk.VBox vboxMain;

		private global::Gtk.HBox hboxBtns;

		private global::Gamma.GtkWidgets.yButton ybtnAddBottleDeposit;

		private global::Gamma.GtkWidgets.yButton ybtnAddEquipmentDeposit;

		private global::Gamma.GtkWidgets.yButton ybtnRemoveDeposit;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTreeView ytreeViewDepositReturnsItems;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.ViewWidgets.Orders.OrderDepositReturnsItemsView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.ViewWidgets.Orders.OrderDepositReturnsItemsView";
			// Container child Vodovoz.ViewWidgets.Orders.OrderDepositReturnsItemsView.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hboxBtns = new global::Gtk.HBox();
			this.hboxBtns.Name = "hboxBtns";
			this.hboxBtns.Spacing = 6;
			// Container child hboxBtns.Gtk.Box+BoxChild
			this.ybtnAddBottleDeposit = new global::Gamma.GtkWidgets.yButton();
			this.ybtnAddBottleDeposit.CanFocus = true;
			this.ybtnAddBottleDeposit.Name = "ybtnAddBottleDeposit";
			this.ybtnAddBottleDeposit.UseUnderline = true;
			this.ybtnAddBottleDeposit.Label = global::Mono.Unix.Catalog.GetString("Бутыли");
			this.hboxBtns.Add(this.ybtnAddBottleDeposit);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hboxBtns[this.ybtnAddBottleDeposit]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hboxBtns.Gtk.Box+BoxChild
			this.ybtnAddEquipmentDeposit = new global::Gamma.GtkWidgets.yButton();
			this.ybtnAddEquipmentDeposit.CanFocus = true;
			this.ybtnAddEquipmentDeposit.Name = "ybtnAddEquipmentDeposit";
			this.ybtnAddEquipmentDeposit.UseUnderline = true;
			this.ybtnAddEquipmentDeposit.Label = global::Mono.Unix.Catalog.GetString("Оборудование");
			this.hboxBtns.Add(this.ybtnAddEquipmentDeposit);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxBtns[this.ybtnAddEquipmentDeposit]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hboxBtns.Gtk.Box+BoxChild
			this.ybtnRemoveDeposit = new global::Gamma.GtkWidgets.yButton();
			this.ybtnRemoveDeposit.CanFocus = true;
			this.ybtnRemoveDeposit.Name = "ybtnRemoveDeposit";
			this.ybtnRemoveDeposit.UseUnderline = true;
			this.ybtnRemoveDeposit.Label = global::Mono.Unix.Catalog.GetString("Удалить");
			this.hboxBtns.Add(this.ybtnRemoveDeposit);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxBtns[this.ybtnRemoveDeposit]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vboxMain.Add(this.hboxBtns);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hboxBtns]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytreeViewDepositReturnsItems = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeViewDepositReturnsItems.CanFocus = true;
			this.ytreeViewDepositReturnsItems.Name = "ytreeViewDepositReturnsItems";
			this.GtkScrolledWindow.Add(this.ytreeViewDepositReturnsItems);
			this.vboxMain.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.GtkScrolledWindow]));
			w6.Position = 1;
			this.Add(this.vboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
