
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Orders
{
	public partial class OrderMainView
	{
		private global::Gtk.VBox vboxMain;

		private global::Gtk.HBox hbox1;

		private global::Gamma.GtkWidgets.yButton ybtnSave;

		private global::Gamma.GtkWidgets.yButton ybtnCancel;

		private global::Gtk.HBox hboxTitle;

		private global::Gamma.GtkWidgets.yLabel ylblTitle;

		private global::Gtk.HBox hboxRadioBtns;

		private global::Gamma.GtkWidgets.yRadioButton yradBtnInfo;

		private global::Gamma.GtkWidgets.yRadioButton yradBtnDocs;

		private global::Gamma.GtkWidgets.yRadioButton yradBtnWorkingOnOrder;

		private global::Gtk.Notebook notebookOrder;

		private global::Gtk.VBox vboxInfo;

		private global::Gtk.Label lblInfo;

		private global::Gtk.VBox vboxOrderDocuments;

		private global::Gtk.Label lblDocuments;

		private global::Gtk.VBox vboxWorkingOnOrder;

		private global::Gtk.Label lblWorkingOnOrder;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Orders.OrderMainView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Orders.OrderMainView";
			// Container child Vodovoz.Views.Orders.OrderMainView.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.WidthRequest = 0;
			this.vboxMain.HeightRequest = 0;
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ybtnSave = new global::Gamma.GtkWidgets.yButton();
			this.ybtnSave.CanFocus = true;
			this.ybtnSave.Name = "ybtnSave";
			this.ybtnSave.UseUnderline = true;
			this.ybtnSave.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
			this.hbox1.Add(this.ybtnSave);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ybtnSave]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ybtnCancel = new global::Gamma.GtkWidgets.yButton();
			this.ybtnCancel.CanFocus = true;
			this.ybtnCancel.Name = "ybtnCancel";
			this.ybtnCancel.UseUnderline = true;
			this.ybtnCancel.Label = global::Mono.Unix.Catalog.GetString("Отмена");
			this.hbox1.Add(this.ybtnCancel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ybtnCancel]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hboxTitle = new global::Gtk.HBox();
			this.hboxTitle.Name = "hboxTitle";
			this.hboxTitle.Spacing = 6;
			// Container child hboxTitle.Gtk.Box+BoxChild
			this.ylblTitle = new global::Gamma.GtkWidgets.yLabel();
			this.ylblTitle.Name = "ylblTitle";
			this.ylblTitle.LabelProp = global::Mono.Unix.Catalog.GetString("<b>ylblTitle</b>");
			this.ylblTitle.UseMarkup = true;
			this.hboxTitle.Add(this.ylblTitle);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxTitle[this.ylblTitle]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			this.hbox1.Add(this.hboxTitle);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hboxTitle]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hboxRadioBtns = new global::Gtk.HBox();
			this.hboxRadioBtns.Name = "hboxRadioBtns";
			this.hboxRadioBtns.Spacing = 6;
			// Container child hboxRadioBtns.Gtk.Box+BoxChild
			this.yradBtnInfo = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradBtnInfo.CanFocus = true;
			this.yradBtnInfo.Name = "yradBtnInfo";
			this.yradBtnInfo.Label = global::Mono.Unix.Catalog.GetString("Информация");
			this.yradBtnInfo.DrawIndicator = false;
			this.yradBtnInfo.UseUnderline = true;
			this.yradBtnInfo.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.hboxRadioBtns.Add(this.yradBtnInfo);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxRadioBtns[this.yradBtnInfo]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hboxRadioBtns.Gtk.Box+BoxChild
			this.yradBtnDocs = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradBtnDocs.CanFocus = true;
			this.yradBtnDocs.Name = "yradBtnDocs";
			this.yradBtnDocs.Label = global::Mono.Unix.Catalog.GetString("Документы");
			this.yradBtnDocs.DrawIndicator = false;
			this.yradBtnDocs.UseUnderline = true;
			this.yradBtnDocs.Group = this.yradBtnInfo.Group;
			this.hboxRadioBtns.Add(this.yradBtnDocs);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxRadioBtns[this.yradBtnDocs]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hboxRadioBtns.Gtk.Box+BoxChild
			this.yradBtnWorkingOnOrder = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradBtnWorkingOnOrder.CanFocus = true;
			this.yradBtnWorkingOnOrder.Name = "yradBtnWorkingOnOrder";
			this.yradBtnWorkingOnOrder.Label = global::Mono.Unix.Catalog.GetString("Работа над заказом");
			this.yradBtnWorkingOnOrder.DrawIndicator = false;
			this.yradBtnWorkingOnOrder.UseUnderline = true;
			this.yradBtnWorkingOnOrder.Group = this.yradBtnInfo.Group;
			this.hboxRadioBtns.Add(this.yradBtnWorkingOnOrder);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxRadioBtns[this.yradBtnWorkingOnOrder]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox1.Add(this.hboxRadioBtns);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hboxRadioBtns]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			this.vboxMain.Add(this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hbox1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.notebookOrder = new global::Gtk.Notebook();
			this.notebookOrder.CanFocus = true;
			this.notebookOrder.Name = "notebookOrder";
			this.notebookOrder.CurrentPage = 0;
			// Container child notebookOrder.Gtk.Notebook+NotebookChild
			this.vboxInfo = new global::Gtk.VBox();
			this.vboxInfo.Name = "vboxInfo";
			this.vboxInfo.Spacing = 6;
			this.notebookOrder.Add(this.vboxInfo);
			// Notebook tab
			this.lblInfo = new global::Gtk.Label();
			this.lblInfo.Name = "lblInfo";
			this.lblInfo.LabelProp = global::Mono.Unix.Catalog.GetString("Информация");
			this.notebookOrder.SetTabLabel(this.vboxInfo, this.lblInfo);
			this.lblInfo.ShowAll();
			// Container child notebookOrder.Gtk.Notebook+NotebookChild
			this.vboxOrderDocuments = new global::Gtk.VBox();
			this.vboxOrderDocuments.Name = "vboxOrderDocuments";
			this.vboxOrderDocuments.Spacing = 6;
			this.notebookOrder.Add(this.vboxOrderDocuments);
			global::Gtk.Notebook.NotebookChild w11 = ((global::Gtk.Notebook.NotebookChild)(this.notebookOrder[this.vboxOrderDocuments]));
			w11.Position = 1;
			// Notebook tab
			this.lblDocuments = new global::Gtk.Label();
			this.lblDocuments.Name = "lblDocuments";
			this.lblDocuments.LabelProp = global::Mono.Unix.Catalog.GetString("Документы");
			this.notebookOrder.SetTabLabel(this.vboxOrderDocuments, this.lblDocuments);
			this.lblDocuments.ShowAll();
			// Container child notebookOrder.Gtk.Notebook+NotebookChild
			this.vboxWorkingOnOrder = new global::Gtk.VBox();
			this.vboxWorkingOnOrder.Name = "vboxWorkingOnOrder";
			this.vboxWorkingOnOrder.Spacing = 6;
			this.notebookOrder.Add(this.vboxWorkingOnOrder);
			global::Gtk.Notebook.NotebookChild w12 = ((global::Gtk.Notebook.NotebookChild)(this.notebookOrder[this.vboxWorkingOnOrder]));
			w12.Position = 2;
			// Notebook tab
			this.lblWorkingOnOrder = new global::Gtk.Label();
			this.lblWorkingOnOrder.Name = "lblWorkingOnOrder";
			this.lblWorkingOnOrder.LabelProp = global::Mono.Unix.Catalog.GetString("Работа над заказом");
			this.notebookOrder.SetTabLabel(this.vboxWorkingOnOrder, this.lblWorkingOnOrder);
			this.lblWorkingOnOrder.ShowAll();
			this.vboxMain.Add(this.notebookOrder);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.notebookOrder]));
			w13.Position = 1;
			this.Add(this.vboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.yradBtnInfo.Toggled += new global::System.EventHandler(this.OnYradBtnInfoToggled);
			this.yradBtnDocs.Toggled += new global::System.EventHandler(this.OnYradBtnDocsToggled);
			this.yradBtnWorkingOnOrder.Toggled += new global::System.EventHandler(this.OnYradBtnWorkingOnOrderToggled);
		}
	}
}
