
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Orders
{
	public partial class DiscountReasonView
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gamma.GtkWidgets.yButton buttonSave;

		private global::Gamma.GtkWidgets.yButton buttonCancel;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Table table3;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label2;

		private global::Gamma.GtkWidgets.yCheckButton checkIsArchive;

		private global::Gtk.HBox hbox4;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label3;

		private global::Gtk.ComboBox comboDiscountTargetType;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label1;

		private global::Gamma.GtkWidgets.yEntry entryName;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label labelPermission;

		private global::Gtk.ComboBox comboPermissionType;

		private global::Gtk.Label labelSkill;

		private global::Gamma.Widgets.yListComboBox comboSkillLevel;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Entry entry2;

		private global::Gtk.Button buttonChoosePermission;

		private global::Gtk.Button buttonClearPermission;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label label5;

		private global::Gtk.Entry entry4;

		private global::Gtk.Label label4;

		private global::Gtk.Entry entry3;

		private global::Gtk.ComboBox combobox3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Orders.DiscountReasonView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Orders.DiscountReasonView";
			// Container child Vodovoz.Views.Orders.DiscountReasonView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonSave = new global::Gamma.GtkWidgets.yButton();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
			global::Gtk.Image w1 = new global::Gtk.Image();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-floppy", global::Gtk.IconSize.Menu);
			this.buttonSave.Image = w1;
			this.hbox1.Add(this.buttonSave);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonSave]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gamma.GtkWidgets.yButton();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Отменить");
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-close", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w3;
			this.hbox1.Add(this.buttonCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonCancel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table(((uint)(1)), ((uint)(3)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("В архиве:");
			this.label2.Justify = ((global::Gtk.Justification)(1));
			this.hbox2.Add(this.label2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label2]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.checkIsArchive = new global::Gamma.GtkWidgets.yCheckButton();
			this.checkIsArchive.CanFocus = true;
			this.checkIsArchive.Name = "checkIsArchive";
			this.checkIsArchive.Label = "";
			this.checkIsArchive.DrawIndicator = true;
			this.checkIsArchive.UseUnderline = true;
			this.hbox2.Add(this.checkIsArchive);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.checkIsArchive]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.table3.Add(this.hbox2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3[this.hbox2]));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Тип");
			this.hbox5.Add(this.label3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label3]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.comboDiscountTargetType = global::Gtk.ComboBox.NewText();
			this.comboDiscountTargetType.Name = "comboDiscountTargetType";
			this.hbox5.Add(this.comboDiscountTargetType);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.comboDiscountTargetType]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.hbox4.Add(this.hbox5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox5]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Название:");
			this.label1.Justify = ((global::Gtk.Justification)(1));
			this.hbox3.Add(this.label1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label1]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entryName = new global::Gamma.GtkWidgets.yEntry();
			this.entryName.CanFocus = true;
			this.entryName.Name = "entryName";
			this.entryName.IsEditable = true;
			this.entryName.InvisibleChar = '•';
			this.hbox3.Add(this.entryName);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entryName]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox4.Add(this.hbox3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox3]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.table3.Add(this.hbox4);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3[this.hbox4]));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add(this.table3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table3]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.labelPermission = new global::Gtk.Label();
			this.labelPermission.Name = "labelPermission";
			this.labelPermission.LabelProp = global::Mono.Unix.Catalog.GetString("Права");
			this.hbox6.Add(this.labelPermission);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.labelPermission]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.comboPermissionType = global::Gtk.ComboBox.NewText();
			this.comboPermissionType.Name = "comboPermissionType";
			this.hbox6.Add(this.comboPermissionType);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.comboPermissionType]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.labelSkill = new global::Gtk.Label();
			this.labelSkill.Name = "labelSkill";
			this.labelSkill.LabelProp = global::Mono.Unix.Catalog.GetString("Квалификация");
			this.hbox6.Add(this.labelSkill);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.labelSkill]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.comboSkillLevel = new global::Gamma.Widgets.yListComboBox();
			this.comboSkillLevel.Name = "comboSkillLevel";
			this.comboSkillLevel.AddIfNotExist = false;
			this.comboSkillLevel.DefaultFirst = false;
			this.hbox6.Add(this.comboSkillLevel);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.comboSkillLevel]));
			w21.Position = 3;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '•';
			this.hbox7.Add(this.entry2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entry2]));
			w22.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.buttonChoosePermission = new global::Gtk.Button();
			this.buttonChoosePermission.CanFocus = true;
			this.buttonChoosePermission.Name = "buttonChoosePermission";
			this.buttonChoosePermission.UseUnderline = true;
			this.buttonChoosePermission.Label = global::Mono.Unix.Catalog.GetString("Choose");
			this.hbox7.Add(this.buttonChoosePermission);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.buttonChoosePermission]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.buttonClearPermission = new global::Gtk.Button();
			this.buttonClearPermission.CanFocus = true;
			this.buttonClearPermission.Name = "buttonClearPermission";
			this.buttonClearPermission.UseUnderline = true;
			this.buttonClearPermission.Label = global::Mono.Unix.Catalog.GetString("Clear");
			this.hbox7.Add(this.buttonClearPermission);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.buttonClearPermission]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox6.Add(this.hbox7);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hbox7]));
			w25.Position = 4;
			this.vbox1.Add(this.hbox6);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox6]));
			w26.Position = 3;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.hbox8.Add(this.label5);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label5]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.entry4 = new global::Gtk.Entry();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '•';
			this.hbox8.Add(this.entry4);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.entry4]));
			w28.Position = 2;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.hbox8.Add(this.label4);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label4]));
			w29.Position = 3;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '•';
			this.hbox8.Add(this.entry3);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.entry3]));
			w30.Position = 4;
			// Container child hbox8.Gtk.Box+BoxChild
			this.combobox3 = global::Gtk.ComboBox.NewText();
			this.combobox3.Name = "combobox3";
			this.hbox8.Add(this.combobox3);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.combobox3]));
			w31.Position = 5;
			w31.Expand = false;
			w31.Fill = false;
			this.vbox1.Add(this.hbox8);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox8]));
			w32.Position = 4;
			w32.Expand = false;
			w32.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
