
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.ViewWidgets.Orders
{
	public partial class OrderInfoExpandedPanelView
	{
		private global::Gtk.HBox hboxMain;

		private global::Gtk.HBox hboxPanel;

		private global::Gamma.GtkWidgets.yButton ybtnExpander;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.ViewWidgets.Orders.OrderInfoExpandedPanelView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.ViewWidgets.Orders.OrderInfoExpandedPanelView";
			// Container child Vodovoz.ViewWidgets.Orders.OrderInfoExpandedPanelView.Gtk.Container+ContainerChild
			this.hboxMain = new global::Gtk.HBox();
			this.hboxMain.Name = "hboxMain";
			this.hboxMain.Spacing = 6;
			// Container child hboxMain.Gtk.Box+BoxChild
			this.hboxPanel = new global::Gtk.HBox();
			this.hboxPanel.Name = "hboxPanel";
			this.hboxPanel.Spacing = 6;
			this.hboxMain.Add(this.hboxPanel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hboxMain[this.hboxPanel]));
			w1.Position = 0;
			// Container child hboxMain.Gtk.Box+BoxChild
			this.ybtnExpander = new global::Gamma.GtkWidgets.yButton();
			this.ybtnExpander.CanFocus = true;
			this.ybtnExpander.Name = "ybtnExpander";
			this.ybtnExpander.UseUnderline = true;
			this.ybtnExpander.Label = global::Mono.Unix.Catalog.GetString("<<");
			this.hboxMain.Add(this.ybtnExpander);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxMain[this.ybtnExpander]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add(this.hboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
