
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Orders
{
	public partial class DiscountsView
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Table datatableDiscounts;

		private global::Gtk.Button buttonAdd;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Orders.DiscountsView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Orders.DiscountsView";
			// Container child Vodovoz.Views.Orders.DiscountsView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.datatableDiscounts = new global::Gtk.Table(((uint)(1)), ((uint)(9)), false);
			this.datatableDiscounts.Name = "datatableDiscounts";
			this.datatableDiscounts.ColumnSpacing = ((uint)(6));
			this.vbox1.Add(this.datatableDiscounts);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.datatableDiscounts]));
			w1.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.buttonAdd = new global::Gtk.Button();
			this.buttonAdd.CanFocus = true;
			this.buttonAdd.Name = "buttonAdd";
			this.buttonAdd.UseUnderline = true;
			this.buttonAdd.Label = global::Mono.Unix.Catalog.GetString("Добавить");
			global::Gtk.Image w2 = new global::Gtk.Image();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
			this.buttonAdd.Image = w2;
			this.vbox1.Add(this.buttonAdd);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.buttonAdd]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
