
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Client
{
	public partial class CounterpartyContractView
	{
		private global::Gtk.VBox vboxMain;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Button buttonSave;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Table datatable5;

		private global::Gamma.GtkWidgets.yCheckButton checkOnCancellation;

		private global::QS.Widgets.GtkUI.DatePicker dateIssue;

		private global::Gamma.GtkWidgets.yEntry entryNumber;

		private global::Gtk.HBox hbox17;

		private global::Gtk.VSeparator vseparator2;

		private global::Gamma.GtkWidgets.yCheckButton checkArchive;

		private global::Gtk.VSeparator vseparator3;

		private global::Gtk.Label lblContractType;

		private global::Gtk.Label lblDateIssue;

		private global::Gtk.Label lblMaxDelay;

		private global::Gtk.Label lblNumber;

		private global::Gtk.Label lblOrganisation;

		private global::Gamma.Widgets.yEntryReference referenceOrganization;

		private global::Gamma.GtkWidgets.ySpinButton spinDelay;

		private global::QSDocTemplates.TemplateWidget templatewidget1;

		private global::Gamma.Widgets.yEnumComboBox ycomboContractType;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Client.CounterpartyContractView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Client.CounterpartyContractView";
			// Container child Vodovoz.Views.Client.CounterpartyContractView.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
			global::Gtk.Image w1 = new global::Gtk.Image();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.Menu);
			this.buttonSave.Image = w1;
			this.hbox4.Add(this.buttonSave);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonSave]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Отменить");
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w3;
			this.hbox4.Add(this.buttonCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonCancel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vboxMain.Add(this.hbox4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hbox4]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.datatable5 = new global::Gtk.Table(((uint)(7)), ((uint)(3)), false);
			this.datatable5.Name = "datatable5";
			this.datatable5.RowSpacing = ((uint)(6));
			this.datatable5.ColumnSpacing = ((uint)(6));
			this.datatable5.BorderWidth = ((uint)(6));
			// Container child datatable5.Gtk.Table+TableChild
			this.checkOnCancellation = new global::Gamma.GtkWidgets.yCheckButton();
			this.checkOnCancellation.CanFocus = true;
			this.checkOnCancellation.Name = "checkOnCancellation";
			this.checkOnCancellation.Label = global::Mono.Unix.Catalog.GetString("На расторжении");
			this.checkOnCancellation.DrawIndicator = true;
			this.checkOnCancellation.UseUnderline = true;
			this.datatable5.Add(this.checkOnCancellation);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.datatable5[this.checkOnCancellation]));
			w6.TopAttach = ((uint)(5));
			w6.BottomAttach = ((uint)(6));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable5.Gtk.Table+TableChild
			this.dateIssue = new global::QS.Widgets.GtkUI.DatePicker();
			this.dateIssue.Sensitive = false;
			this.dateIssue.Events = ((global::Gdk.EventMask)(256));
			this.dateIssue.Name = "dateIssue";
			this.dateIssue.WithTime = false;
			this.dateIssue.HideCalendarButton = false;
			this.dateIssue.Date = new global::System.DateTime(0);
			this.dateIssue.IsEditable = true;
			this.dateIssue.AutoSeparation = false;
			this.datatable5.Add(this.dateIssue);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.datatable5[this.dateIssue]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable5.Gtk.Table+TableChild
			this.entryNumber = new global::Gamma.GtkWidgets.yEntry();
			this.entryNumber.Sensitive = false;
			this.entryNumber.CanFocus = true;
			this.entryNumber.Name = "entryNumber";
			this.entryNumber.IsEditable = false;
			this.entryNumber.InvisibleChar = '●';
			this.datatable5.Add(this.entryNumber);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.datatable5[this.entryNumber]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable5.Gtk.Table+TableChild
			this.hbox17 = new global::Gtk.HBox();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator();
			this.vseparator2.Name = "vseparator2";
			this.hbox17.Add(this.vseparator2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.vseparator2]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.checkArchive = new global::Gamma.GtkWidgets.yCheckButton();
			this.checkArchive.CanFocus = true;
			this.checkArchive.Name = "checkArchive";
			this.checkArchive.Label = global::Mono.Unix.Catalog.GetString("Архивный");
			this.checkArchive.DrawIndicator = true;
			this.checkArchive.UseUnderline = true;
			this.hbox17.Add(this.checkArchive);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.checkArchive]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator();
			this.vseparator3.Name = "vseparator3";
			this.hbox17.Add(this.vseparator3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.vseparator3]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.datatable5.Add(this.hbox17);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.datatable5[this.hbox17]));
			w12.TopAttach = ((uint)(5));
			w12.BottomAttach = ((uint)(6));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable5.Gtk.Table+TableChild
			this.lblContractType = new global::Gtk.Label();
			this.lblContractType.Name = "lblContractType";
			this.lblContractType.Xalign = 1F;
			this.lblContractType.LabelProp = global::Mono.Unix.Catalog.GetString("Тип договора:");
			this.datatable5.Add(this.lblContractType);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.datatable5[this.lblContractType]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable5.Gtk.Table+TableChild
			this.lblDateIssue = new global::Gtk.Label();
			this.lblDateIssue.Name = "lblDateIssue";
			this.lblDateIssue.Xalign = 1F;
			this.lblDateIssue.LabelProp = global::Mono.Unix.Catalog.GetString("Дата заключения:");
			this.datatable5.Add(this.lblDateIssue);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.datatable5[this.lblDateIssue]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable5.Gtk.Table+TableChild
			this.lblMaxDelay = new global::Gtk.Label();
			this.lblMaxDelay.Name = "lblMaxDelay";
			this.lblMaxDelay.Xalign = 1F;
			this.lblMaxDelay.LabelProp = global::Mono.Unix.Catalog.GetString("Максимальный срок отсрочки:");
			this.datatable5.Add(this.lblMaxDelay);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.datatable5[this.lblMaxDelay]));
			w15.TopAttach = ((uint)(4));
			w15.BottomAttach = ((uint)(5));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable5.Gtk.Table+TableChild
			this.lblNumber = new global::Gtk.Label();
			this.lblNumber.Name = "lblNumber";
			this.lblNumber.Xalign = 1F;
			this.lblNumber.LabelProp = global::Mono.Unix.Catalog.GetString("Номер:");
			this.datatable5.Add(this.lblNumber);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.datatable5[this.lblNumber]));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable5.Gtk.Table+TableChild
			this.lblOrganisation = new global::Gtk.Label();
			this.lblOrganisation.Name = "lblOrganisation";
			this.lblOrganisation.Xalign = 1F;
			this.lblOrganisation.LabelProp = global::Mono.Unix.Catalog.GetString("Организация:");
			this.datatable5.Add(this.lblOrganisation);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.datatable5[this.lblOrganisation]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable5.Gtk.Table+TableChild
			this.referenceOrganization = new global::Gamma.Widgets.yEntryReference();
			this.referenceOrganization.Sensitive = false;
			this.referenceOrganization.Events = ((global::Gdk.EventMask)(256));
			this.referenceOrganization.Name = "referenceOrganization";
			this.datatable5.Add(this.referenceOrganization);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.datatable5[this.referenceOrganization]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable5.Gtk.Table+TableChild
			this.spinDelay = new global::Gamma.GtkWidgets.ySpinButton(0D, 100D, 1D);
			this.spinDelay.CanFocus = true;
			this.spinDelay.Name = "spinDelay";
			this.spinDelay.Adjustment.PageIncrement = 10D;
			this.spinDelay.ClimbRate = 1D;
			this.spinDelay.Numeric = true;
			this.spinDelay.Value = 3D;
			this.spinDelay.ValueAsDecimal = 0m;
			this.spinDelay.ValueAsInt = 0;
			this.datatable5.Add(this.spinDelay);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.datatable5[this.spinDelay]));
			w19.TopAttach = ((uint)(4));
			w19.BottomAttach = ((uint)(5));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable5.Gtk.Table+TableChild
			this.templatewidget1 = new global::QSDocTemplates.TemplateWidget();
			this.templatewidget1.Events = ((global::Gdk.EventMask)(256));
			this.templatewidget1.Name = "templatewidget1";
			this.templatewidget1.CanRevertCommon = false;
			this.datatable5.Add(this.templatewidget1);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.datatable5[this.templatewidget1]));
			w20.BottomAttach = ((uint)(6));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable5.Gtk.Table+TableChild
			this.ycomboContractType = new global::Gamma.Widgets.yEnumComboBox();
			this.ycomboContractType.Sensitive = false;
			this.ycomboContractType.Name = "ycomboContractType";
			this.ycomboContractType.ShowSpecialStateAll = false;
			this.ycomboContractType.ShowSpecialStateNot = false;
			this.ycomboContractType.UseShortTitle = false;
			this.ycomboContractType.DefaultFirst = false;
			this.datatable5.Add(this.ycomboContractType);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.datatable5[this.ycomboContractType]));
			w21.TopAttach = ((uint)(3));
			w21.BottomAttach = ((uint)(4));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxMain.Add(this.datatable5);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.datatable5]));
			w22.Position = 1;
			this.Add(this.vboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
