
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Orders
{
	public partial class SelfDeliveryOrderInfoPanelView
	{
		private global::Gtk.VBox vboxInfo;

		private global::Gtk.Table tableInfo;

		private global::QS.Views.Control.EntityEntry counterpartyEntry;

		private global::QS.Widgets.GtkUI.DatePicker datePickerDeliveryDate;

		private global::Gamma.Widgets.yEnumComboBox enumDocumentType;

		private global::Gamma.Widgets.yEnumComboBox enumPaymentType;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTextView ytxtViewComment;

		private global::Gtk.HBox hbxOnlineOrder;

		private global::Gamma.GtkWidgets.yLabel ylblOnlineOrder;

		private global::Gamma.Widgets.yValidatedEntry entOnlineOrder;

		private global::Gamma.Widgets.ySpecComboBox ySpecPaymentFrom;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Label lblPaymentType;

		private global::QS.Widgets.GtkUI.DatePicker pickerBillDate;

		private global::Gamma.Widgets.yEntryReference referenceDeliverySchedule;

		private global::Gamma.GtkWidgets.yCheckButton ycheckAddCertificates;

		private global::Gamma.GtkWidgets.yCheckButton ycheckContactlessDelivery;

		private global::Gamma.GtkWidgets.yCheckButton ycheckPaymentBySMS;

		private global::Gamma.GtkWidgets.yLabel ylblAuthor;

		private global::Gamma.GtkWidgets.yLabel ylblBillDate;

		private global::Gamma.GtkWidgets.yLabel ylblComment;

		private global::Gamma.GtkWidgets.yLabel ylblCounterparty;

		private global::Gamma.GtkWidgets.yLabel ylblCreated;

		private global::Gamma.GtkWidgets.yLabel ylblCreationDate;

		private global::Gamma.GtkWidgets.yLabel ylblDeliveryDate;

		private global::Gamma.GtkWidgets.yLabel ylblDeliveryTime;

		private global::Gamma.GtkWidgets.yLabel ylblDocumentType;

		private global::Gamma.GtkWidgets.yLabel ylblExtraService;

		private global::Gamma.GtkWidgets.yLabel ylblOrderAuthor;

		private global::Gamma.GtkWidgets.yLabel ylblStatus;

		private global::Gamma.GtkWidgets.yLabel ylblStatusInfo;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Orders.SelfDeliveryOrderInfoPanelView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Orders.SelfDeliveryOrderInfoPanelView";
			// Container child Vodovoz.Views.Orders.SelfDeliveryOrderInfoPanelView.Gtk.Container+ContainerChild
			this.vboxInfo = new global::Gtk.VBox();
			this.vboxInfo.Name = "vboxInfo";
			this.vboxInfo.Spacing = 6;
			// Container child vboxInfo.Gtk.Box+BoxChild
			this.tableInfo = new global::Gtk.Table(((uint)(12)), ((uint)(5)), false);
			this.tableInfo.Name = "tableInfo";
			this.tableInfo.RowSpacing = ((uint)(6));
			this.tableInfo.ColumnSpacing = ((uint)(6));
			// Container child tableInfo.Gtk.Table+TableChild
			this.counterpartyEntry = new global::QS.Views.Control.EntityEntry();
			this.counterpartyEntry.Events = ((global::Gdk.EventMask)(256));
			this.counterpartyEntry.Name = "counterpartyEntry";
			this.tableInfo.Add(this.counterpartyEntry);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.counterpartyEntry]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(5));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.datePickerDeliveryDate = new global::QS.Widgets.GtkUI.DatePicker();
			this.datePickerDeliveryDate.Events = ((global::Gdk.EventMask)(256));
			this.datePickerDeliveryDate.Name = "datePickerDeliveryDate";
			this.datePickerDeliveryDate.WithTime = false;
			this.datePickerDeliveryDate.HideCalendarButton = false;
			this.datePickerDeliveryDate.Date = new global::System.DateTime(0);
			this.datePickerDeliveryDate.IsEditable = false;
			this.datePickerDeliveryDate.AutoSeparation = false;
			this.tableInfo.Add(this.datePickerDeliveryDate);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.datePickerDeliveryDate]));
			w2.TopAttach = ((uint)(3));
			w2.BottomAttach = ((uint)(4));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.enumDocumentType = new global::Gamma.Widgets.yEnumComboBox();
			this.enumDocumentType.Name = "enumDocumentType";
			this.enumDocumentType.ShowSpecialStateAll = false;
			this.enumDocumentType.ShowSpecialStateNot = false;
			this.enumDocumentType.UseShortTitle = false;
			this.enumDocumentType.DefaultFirst = false;
			this.tableInfo.Add(this.enumDocumentType);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.enumDocumentType]));
			w3.TopAttach = ((uint)(5));
			w3.BottomAttach = ((uint)(6));
			w3.LeftAttach = ((uint)(4));
			w3.RightAttach = ((uint)(5));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.enumPaymentType = new global::Gamma.Widgets.yEnumComboBox();
			this.enumPaymentType.Name = "enumPaymentType";
			this.enumPaymentType.ShowSpecialStateAll = false;
			this.enumPaymentType.ShowSpecialStateNot = false;
			this.enumPaymentType.UseShortTitle = false;
			this.enumPaymentType.DefaultFirst = false;
			this.tableInfo.Add(this.enumPaymentType);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.enumPaymentType]));
			w4.TopAttach = ((uint)(4));
			w4.BottomAttach = ((uint)(5));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytxtViewComment = new global::Gamma.GtkWidgets.yTextView();
			this.ytxtViewComment.CanFocus = true;
			this.ytxtViewComment.Name = "ytxtViewComment";
			this.GtkScrolledWindow.Add(this.ytxtViewComment);
			this.tableInfo.Add(this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.GtkScrolledWindow]));
			w6.TopAttach = ((uint)(7));
			w6.BottomAttach = ((uint)(11));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.hbxOnlineOrder = new global::Gtk.HBox();
			this.hbxOnlineOrder.Name = "hbxOnlineOrder";
			this.hbxOnlineOrder.Spacing = 6;
			// Container child hbxOnlineOrder.Gtk.Box+BoxChild
			this.ylblOnlineOrder = new global::Gamma.GtkWidgets.yLabel();
			this.ylblOnlineOrder.Name = "ylblOnlineOrder";
			this.ylblOnlineOrder.Xalign = 1F;
			this.ylblOnlineOrder.LabelProp = global::Mono.Unix.Catalog.GetString("Онлайн заказ:");
			this.hbxOnlineOrder.Add(this.ylblOnlineOrder);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbxOnlineOrder[this.ylblOnlineOrder]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbxOnlineOrder.Gtk.Box+BoxChild
			this.entOnlineOrder = new global::Gamma.Widgets.yValidatedEntry();
			this.entOnlineOrder.CanFocus = true;
			this.entOnlineOrder.Name = "entOnlineOrder";
			this.entOnlineOrder.IsEditable = true;
			this.entOnlineOrder.MaxLength = 10;
			this.entOnlineOrder.InvisibleChar = '●';
			this.hbxOnlineOrder.Add(this.entOnlineOrder);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbxOnlineOrder[this.entOnlineOrder]));
			w8.Position = 1;
			w8.Expand = false;
			// Container child hbxOnlineOrder.Gtk.Box+BoxChild
			this.ySpecPaymentFrom = new global::Gamma.Widgets.ySpecComboBox();
			this.ySpecPaymentFrom.Name = "ySpecPaymentFrom";
			this.ySpecPaymentFrom.AddIfNotExist = false;
			this.ySpecPaymentFrom.DefaultFirst = false;
			this.ySpecPaymentFrom.ShowSpecialStateAll = false;
			this.ySpecPaymentFrom.ShowSpecialStateNot = false;
			this.hbxOnlineOrder.Add(this.ySpecPaymentFrom);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbxOnlineOrder[this.ySpecPaymentFrom]));
			w9.Position = 2;
			this.tableInfo.Add(this.hbxOnlineOrder);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.hbxOnlineOrder]));
			w10.TopAttach = ((uint)(4));
			w10.BottomAttach = ((uint)(5));
			w10.LeftAttach = ((uint)(3));
			w10.RightAttach = ((uint)(5));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.tableInfo.Add(this.hseparator1);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.hseparator1]));
			w11.TopAttach = ((uint)(6));
			w11.BottomAttach = ((uint)(7));
			w11.RightAttach = ((uint)(5));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.lblPaymentType = new global::Gtk.Label();
			this.lblPaymentType.Name = "lblPaymentType";
			this.lblPaymentType.Xalign = 1F;
			this.lblPaymentType.LabelProp = global::Mono.Unix.Catalog.GetString("Форма оплаты:");
			this.tableInfo.Add(this.lblPaymentType);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.lblPaymentType]));
			w12.TopAttach = ((uint)(4));
			w12.BottomAttach = ((uint)(5));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.pickerBillDate = new global::QS.Widgets.GtkUI.DatePicker();
			this.pickerBillDate.Events = ((global::Gdk.EventMask)(256));
			this.pickerBillDate.Name = "pickerBillDate";
			this.pickerBillDate.WithTime = false;
			this.pickerBillDate.HideCalendarButton = false;
			this.pickerBillDate.Date = new global::System.DateTime(0);
			this.pickerBillDate.IsEditable = true;
			this.pickerBillDate.AutoSeparation = true;
			this.tableInfo.Add(this.pickerBillDate);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.pickerBillDate]));
			w13.TopAttach = ((uint)(5));
			w13.BottomAttach = ((uint)(6));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.referenceDeliverySchedule = new global::Gamma.Widgets.yEntryReference();
			this.referenceDeliverySchedule.Events = ((global::Gdk.EventMask)(256));
			this.referenceDeliverySchedule.Name = "referenceDeliverySchedule";
			this.tableInfo.Add(this.referenceDeliverySchedule);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.referenceDeliverySchedule]));
			w14.TopAttach = ((uint)(3));
			w14.BottomAttach = ((uint)(4));
			w14.LeftAttach = ((uint)(4));
			w14.RightAttach = ((uint)(5));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ycheckAddCertificates = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckAddCertificates.CanFocus = true;
			this.ycheckAddCertificates.Name = "ycheckAddCertificates";
			this.ycheckAddCertificates.Label = global::Mono.Unix.Catalog.GetString("Сертификаты");
			this.ycheckAddCertificates.DrawIndicator = true;
			this.ycheckAddCertificates.UseUnderline = true;
			this.tableInfo.Add(this.ycheckAddCertificates);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ycheckAddCertificates]));
			w15.TopAttach = ((uint)(10));
			w15.BottomAttach = ((uint)(11));
			w15.LeftAttach = ((uint)(4));
			w15.RightAttach = ((uint)(5));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ycheckContactlessDelivery = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckContactlessDelivery.CanFocus = true;
			this.ycheckContactlessDelivery.Name = "ycheckContactlessDelivery";
			this.ycheckContactlessDelivery.Label = global::Mono.Unix.Catalog.GetString("Бесконтактная\nдоставка");
			this.ycheckContactlessDelivery.DrawIndicator = true;
			this.ycheckContactlessDelivery.UseUnderline = true;
			this.tableInfo.Add(this.ycheckContactlessDelivery);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ycheckContactlessDelivery]));
			w16.TopAttach = ((uint)(9));
			w16.BottomAttach = ((uint)(10));
			w16.LeftAttach = ((uint)(4));
			w16.RightAttach = ((uint)(5));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ycheckPaymentBySMS = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckPaymentBySMS.CanFocus = true;
			this.ycheckPaymentBySMS.Name = "ycheckPaymentBySMS";
			this.ycheckPaymentBySMS.Label = global::Mono.Unix.Catalog.GetString("Оплата по СМС");
			this.ycheckPaymentBySMS.DrawIndicator = true;
			this.ycheckPaymentBySMS.UseUnderline = true;
			this.tableInfo.Add(this.ycheckPaymentBySMS);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ycheckPaymentBySMS]));
			w17.TopAttach = ((uint)(8));
			w17.BottomAttach = ((uint)(9));
			w17.LeftAttach = ((uint)(4));
			w17.RightAttach = ((uint)(5));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ylblAuthor = new global::Gamma.GtkWidgets.yLabel();
			this.ylblAuthor.Name = "ylblAuthor";
			this.ylblAuthor.Xalign = 1F;
			this.ylblAuthor.LabelProp = global::Mono.Unix.Catalog.GetString("Автор:");
			this.tableInfo.Add(this.ylblAuthor);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ylblAuthor]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ylblBillDate = new global::Gamma.GtkWidgets.yLabel();
			this.ylblBillDate.Name = "ylblBillDate";
			this.ylblBillDate.Xalign = 1F;
			this.ylblBillDate.LabelProp = global::Mono.Unix.Catalog.GetString("Дата счета:");
			this.tableInfo.Add(this.ylblBillDate);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ylblBillDate]));
			w19.TopAttach = ((uint)(5));
			w19.BottomAttach = ((uint)(6));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ylblComment = new global::Gamma.GtkWidgets.yLabel();
			this.ylblComment.Name = "ylblComment";
			this.ylblComment.Xalign = 1F;
			this.ylblComment.LabelProp = global::Mono.Unix.Catalog.GetString("Комментарий:");
			this.tableInfo.Add(this.ylblComment);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ylblComment]));
			w20.TopAttach = ((uint)(7));
			w20.BottomAttach = ((uint)(8));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ylblCounterparty = new global::Gamma.GtkWidgets.yLabel();
			this.ylblCounterparty.Name = "ylblCounterparty";
			this.ylblCounterparty.Xalign = 1F;
			this.ylblCounterparty.LabelProp = global::Mono.Unix.Catalog.GetString("Клиент:");
			this.tableInfo.Add(this.ylblCounterparty);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ylblCounterparty]));
			w21.TopAttach = ((uint)(2));
			w21.BottomAttach = ((uint)(3));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ylblCreated = new global::Gamma.GtkWidgets.yLabel();
			this.ylblCreated.Name = "ylblCreated";
			this.ylblCreated.Xalign = 1F;
			this.ylblCreated.LabelProp = global::Mono.Unix.Catalog.GetString("Создан:");
			this.tableInfo.Add(this.ylblCreated);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ylblCreated]));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ylblCreationDate = new global::Gamma.GtkWidgets.yLabel();
			this.ylblCreationDate.Name = "ylblCreationDate";
			this.ylblCreationDate.Xalign = 0F;
			this.ylblCreationDate.LabelProp = global::Mono.Unix.Catalog.GetString("\"Дата создания\"");
			this.tableInfo.Add(this.ylblCreationDate);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ylblCreationDate]));
			w23.LeftAttach = ((uint)(3));
			w23.RightAttach = ((uint)(4));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ylblDeliveryDate = new global::Gamma.GtkWidgets.yLabel();
			this.ylblDeliveryDate.Name = "ylblDeliveryDate";
			this.ylblDeliveryDate.Xalign = 1F;
			this.ylblDeliveryDate.LabelProp = global::Mono.Unix.Catalog.GetString("Дата доставки:");
			this.tableInfo.Add(this.ylblDeliveryDate);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ylblDeliveryDate]));
			w24.TopAttach = ((uint)(3));
			w24.BottomAttach = ((uint)(4));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ylblDeliveryTime = new global::Gamma.GtkWidgets.yLabel();
			this.ylblDeliveryTime.Name = "ylblDeliveryTime";
			this.ylblDeliveryTime.Xalign = 1F;
			this.ylblDeliveryTime.LabelProp = global::Mono.Unix.Catalog.GetString("Интервал:");
			this.tableInfo.Add(this.ylblDeliveryTime);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ylblDeliveryTime]));
			w25.TopAttach = ((uint)(3));
			w25.BottomAttach = ((uint)(4));
			w25.LeftAttach = ((uint)(3));
			w25.RightAttach = ((uint)(4));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ylblDocumentType = new global::Gamma.GtkWidgets.yLabel();
			this.ylblDocumentType.Name = "ylblDocumentType";
			this.ylblDocumentType.Xalign = 1F;
			this.ylblDocumentType.LabelProp = global::Mono.Unix.Catalog.GetString("Тип документов:");
			this.tableInfo.Add(this.ylblDocumentType);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ylblDocumentType]));
			w26.TopAttach = ((uint)(5));
			w26.BottomAttach = ((uint)(6));
			w26.LeftAttach = ((uint)(3));
			w26.RightAttach = ((uint)(4));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ylblExtraService = new global::Gamma.GtkWidgets.yLabel();
			this.ylblExtraService.Name = "ylblExtraService";
			this.ylblExtraService.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Дополнительные\nуслуги</b>");
			this.ylblExtraService.UseMarkup = true;
			this.tableInfo.Add(this.ylblExtraService);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ylblExtraService]));
			w27.TopAttach = ((uint)(7));
			w27.BottomAttach = ((uint)(8));
			w27.LeftAttach = ((uint)(4));
			w27.RightAttach = ((uint)(5));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ylblOrderAuthor = new global::Gamma.GtkWidgets.yLabel();
			this.ylblOrderAuthor.Name = "ylblOrderAuthor";
			this.ylblOrderAuthor.Xalign = 0F;
			this.ylblOrderAuthor.LabelProp = global::Mono.Unix.Catalog.GetString("\"Автор заказа\"");
			this.tableInfo.Add(this.ylblOrderAuthor);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ylblOrderAuthor]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ylblStatus = new global::Gamma.GtkWidgets.yLabel();
			this.ylblStatus.Name = "ylblStatus";
			this.ylblStatus.Xalign = 1F;
			this.ylblStatus.LabelProp = global::Mono.Unix.Catalog.GetString("Статус:");
			this.tableInfo.Add(this.ylblStatus);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ylblStatus]));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.ylblStatusInfo = new global::Gamma.GtkWidgets.yLabel();
			this.ylblStatusInfo.Name = "ylblStatusInfo";
			this.ylblStatusInfo.Xalign = 0F;
			this.ylblStatusInfo.LabelProp = global::Mono.Unix.Catalog.GetString("Статус заказа");
			this.tableInfo.Add(this.ylblStatusInfo);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.ylblStatusInfo]));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxInfo.Add(this.tableInfo);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vboxInfo[this.tableInfo]));
			w31.Position = 0;
			this.Add(this.vboxInfo);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
